[theme]
base="light"
primaryColor="#8E7DBE"        # Soft peach for the accent
backgroundColor="#F7CFD8"     # Light background
secondaryBackgroundColor="#f0eef6"  # Light grayish background for secondary areas
textColor="#413366"           # Dark gray text
font="monospace"             # Clean, modern font